services:
  backend:
    image: wassim560/akida-back:latest
    container_name: akida-back
    ports:
      - "8081:8081"
    networks:
      - akida-network

  frontend:
    image: wassim560/akida-front:latest
    container_name: akida-front
    ports:
      - "8082:80"
    depends_on:
      - backend
    networks:
      - akida-network

networks:
  akida-network:
    external: true
